#!/usr/bin/env bash

# Create SSH tunnel to EventLogging databases through stat1003.
# Replace s1-analytics-slave.eqiad.wmnet with any other host if you need.
ssh -L 3307:s1-analytics-slave.eqiad.wmnet:3306 stat1003.eqiad.wmnet
